apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-monitor
spec:
  selector:
    matchLabels: 
      name: app-check-log-security
  template: 
    metadata:
      labels:
        name: app-check-log-security
    spec:
      nodeSelector: 
        appName: sales 
      
      volumes:
        - name: temp
          hostPath:
            path: /Users/skhurana1
      containers:
      - name: java-log-security-daemon
        image: logchecker:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name : temp
            mountPath: /tmp1
       
 

