apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job-every-fifteen-minutes
spec:
  # left to right ---> Minute Hour Day of month Month Day of week.
  schedule: "0,15,30,45 * * * *"  #run at the 0, 15, 30 and 45 minutes of every hour, every day.
  jobTemplate:
    spec:
      template:   #The template for the Job resources that will be created by this CronJob
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job