apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh-configmap-as-files-in-vol

spec:
   containers:
   - image: java-docker_skh:latest
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     imagePullPolicy: IfNotPresent
     volumeMounts:
        - name: myconfig
          mountPath: /etc/myconfigDir/

   volumes:
   - name: myconfig
     configMap:
       name: customconfig   # vol refering to customConfig configMap  
       items:
       - key: DB_URL
         path: dbUrlFileName # this will the file name under /etc/mycondigDir having value of DB_URL
       - key: debugValue
         path: debugValueFileName 

   
