apiVersion: v1
kind: Pod
metadata:
  name: k8-docker-image-pod

spec:
  containers:
  - image : skhurana333/spring_boot_example:1.0.0
    name: my-spring-boot-app  
  imagePullSecrets:
  - name: myregistrysecret
    
