# one time - kubectl create namespace deleteme
# kubectl delete po uip-adaptor
# kubectl create -f k8-pods.yaml -n deleteme
# kubectl get pods -n deleteme
# For one of the pods in above list
#    kubectl get po  uip-adaptor  -o yaml -n deleteme
# kubectl logs  uip-adaptor -n deleteme

# delete
apiVersion: v1
kind: Pod
metadata:
  name: uip-adaptor

spec:
   containers:
   - image: intuit_uip_adaptor:latest
     imagePullPolicy: IfNotPresent
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo hello; sleep 10;done"]
     #command: ["/bin/sh"]
     name: uip-adaptor
     ports:
       - containerPort: 80
     #livenessProbe:  #todo check why liveeness probe keeps failing
     #  httpGet:
     #    path: /
     #    port: 80
     #  periodSeconds: 20
     #  timeoutSeconds: 5
