apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh-ns
  namespace: my-namespace

spec:
   containers:
   - image: java-docker_skh:latest
     imagePullPolicy: IfNotPresent
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     livenessProbe:
       httpGet:
         path: /
         port: 8080
       periodSeconds: 20
       timeoutSeconds: 15
