# one time - kubectl create namespace deleteme
# kubectl delete po uip-adaptor
# kubectl create -f k8-pods.yaml -n deleteme
# kubectl get pods -n deleteme
# For one of the pods in above list
#    kubectl get po  uip-adaptor  -o yaml -n deleteme
# kubectl logs  uip-adaptor -n deleteme

# delete
apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh

spec:
   containers:
   - image: java-docker_skh:latest
     imagePullPolicy: IfNotPresent
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     livenessProbe:
       httpGet:
         path: /
         port: 8080
       periodSeconds: 20
       timeoutSeconds: 5
