apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh
  labels:
    purpose: args-demo
spec:
  containers:
  - name: k8-args
    image: java-docker_skh:latest
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.arguments=--DB_URL=mysql://localhost:3306/app"]
    imagePullPolicy: IfNotPresent
