apiVersion: v1
kind: Pod
metadata:
  name: k8-secret-pod

spec:
   containers:
   - image: java-docker_skh:latest
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     imagePullPolicy: IfNotPresent
     volumeMounts:
        - name: thesecrets
          mountPath: /etc/allsecrets


   volumes:
   - name: thesecrets
     secret:
        secretName: secretsfromdir


   
