apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh-secrets-injected

spec:
   containers:
   - image: java-docker_skh:latest
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     imagePullPolicy: IfNotPresent
     env:
       - name: db_password  # same as in application.properties
         valueFrom: 
           secretKeyRef:
             name: my-secrets # the K8 secret object 
             key: dbpw
       - name: client_secret  # same as in application.properties
         valueFrom:
           secretKeyRef:
             name: my-secrets # the K8 secret object
             key: clientsecret


   
