#
apiVersion: v1
kind: Service
metadata:
  name: external-service  # this name should match name of endpoint object
                          #(in k8-endpointresource_forservice.yaml)
spec:                   # service without selector
  ports:
    - port: 80