#  kubectl get pods --show-labels
#  kubectl create -f k8-service.yaml
#  kubectl get svc
apiVersion: v1
kind: Service
metadata:
  name: intuit-uip-adaptor
spec:
  ports:
    - port: 80          # service available on this port
      targetPort: 80  # container port the service will forward to
  selector:
    app: uip-adapter-rc # all pods with app=uip-adapter-rc will be par of this