#  kubectl create -f k8_service_exposed_nodeport.yaml
#  kubectl get svc test-nodeport
apiVersion: v1
kind: Service
metadata:
  name: test-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30123
  selector:
    app: intuit-uip-adaptor