apiVersion: apps/v1         
kind: Deployment                  
metadata:
  name: tips-app-depl-maxsurge                    
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels: 
      app: tips-app
  template:  
    metadata:
      name: tips-app
      labels:
        app: tips-app
    spec:
      containers:
      - image: java-docker_skh:latest
        imagePullPolicy: IfNotPresent
        name: tips-app-container
