apiVersion: v1
kind: Service
metadata:
  name: java-tips-svc-namedports
spec:
  ports:
  - name: http              
    port: 80               
    targetPort: http # changed from 8080 to http, same as in pod.spec.containers.port       
  - name: https            
    port: 443              
    targetPort: https
  selector:
    app: named-ports       
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-namedports
  labels:
    app: named-ports
spec:
   containers:
   - image: java_docker_skh:latest
     imagePullPolicy: IfNotPresent
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     ports:
       - name: http  # name of the port
         containerPort: 8080
       - name: https # name of the port
         containerPort: 8443           
