apiVersion: v1
kind: Pod
metadata:
  name: mysql-demo-pod
spec:
  containers:
  - image: mysql
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Test1234
    volumeMounts:
    - name: mysql-data
      mountPath: /Users/skhurana1/data/db
    ports:
    - containerPort: 3306
      protocol: TCP
  volumes:
  - name: mysql-data
    persistentVolumeClaim:          
      claimName: mysql-pvc # same as in pvc definition        
