apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh

spec:
   volumes:
     - name: temp
       hostPath:
         path: /Users/skhurana1
   containers:
   - image: java-docker_skh:latest
     imagePullPolicy: IfNotPresent
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     volumeMounts: 
     - name : temp
       mountPath: /tmp1
