apiVersion: v1
kind: Pod
metadata:
  name: java-docker-skh-for-gpu
spec:
  nodeSelector:               
    gpu: "true"           
  containers:
  - image: java-docker_skh
    name: java-docker-skh-for-gpu
    imagePullPolicy: IfNotPresent
