apiVersion: v1
kind: Pod
metadata:
  name: java-tips-pod

spec:
   containers:
   - image: java-docker_skh:latest
     imagePullPolicy: IfNotPresent
     command: ["./mvnw", "spring-boot:run"]
     name: java-docker-skh
     readinessProbe:
       initialDelaySeconds:2 
       periodSeconds: 10
       timeoutSeconds: 2
       successThreshold: 1
       failureThreshold: 1
       httpGet:
         host:
         scheme: HTTP
         path: /info
        

        
