apiVersion: v1
kind: ReplicationController # this manifests define a replication controller
metadata:
  name: java-docker-skh-rc # name of this replication controller
spec:
  replicas: 2  # desired number of pod instances
  selector: # pod selector determining what pods the rc is operating on
    app: java-docker-skh
  template:  # pod template for creating new pods
    metadata:
      labels:
        app: java-docker-skh  # app label value for pods
    spec:
      containers:
        - name: java-docker-skh-rc
          image: java_docker_skh:9.0
          imagePullPolicy: IfNotPresent
          command: ["./mvnw", "spring-boot:run"]
          ports:
            - containerPort: 8080
