apiVersion: v1
kind: Pod
metadata:
  name: java-tips
  labels:
    app: java-tips-backend
spec:
  containers:
  - image: java-docker_skh:latest
    imagePullPolicy: IfNotPresent
    command: ["./mvnw", "spring-boot:run"]
    name: java-docker-skh

---
apiVersion: v1
kind: Service
metadata:
  name: java-tips-service
spec:
  ports:
    - port: 7777          # service available on this port
      targetPort: 8080  # container port the service will forward to
  selector:
    app: java-tips-backend # all pods with app=java-tips-backend will be part of this
